# Generated by Django 4.2.1 on 2023-06-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название города')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название подборки')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('photo', models.ImageField(blank=True, upload_to='events_photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название подборки')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('photo', models.ImageField(blank=True, upload_to='events_photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Регионы')),
            ],
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('photo', models.ImageField(upload_to='photos_routers/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=100, verbose_name='описание')),
                ('link_1', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_2', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_3', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_4', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_5', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_6', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.cities', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.CharField(max_length=100, verbose_name='описание')),
                ('link_1', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_2', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_3', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_4', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_5', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_6', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.cities', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('how_to_get_there', models.CharField(max_length=255, verbose_name='Как добраться')),
                ('how_to_get_there_desc', models.TextField(verbose_name='Описание')),
                ('stopping_points', models.CharField(max_length=255, verbose_name='Путкты остановки')),
                ('stopping_points_desc', models.TextField(verbose_name='Описания города')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.routers', verbose_name='Маршруты')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosDiscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описане')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_7', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_8', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_9', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('external_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.photos', verbose_name='Рубрика фотографий')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('discription', models.CharField(max_length=100, verbose_name='описание')),
                ('link_1', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_2', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_3', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_4', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_5', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_6', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.cities', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.CharField(max_length=100, verbose_name='описание')),
                ('link_1', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_2', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_3', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_4', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_5', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_6', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.cities', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Events_ditails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='events_photo/%Y/%m/%d/', verbose_name='Фото')),
                ('date', models.TextField(verbose_name='Дата проведения события')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоймость')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на источник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.events', verbose_name='События')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.CharField(max_length=100, verbose_name='описание')),
                ('link_1', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_2', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_3', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_4', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_5', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('link_6', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('photo_1', models.ImageField(blank=True, upload_to='cultural_objects/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='cultural_objects/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_3', models.ImageField(blank=True, upload_to='cultural_objects/%Y/%m/%d/', verbose_name='Фото')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.cities', verbose_name='Город')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.region', verbose_name='Регионы'),
        ),
    ]
