# Generated by Django 4.2.1 on 2023-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='discription',
            field=models.TextField(verbose_name='описание'),
        ),
    ]
