# Generated by Django 4.2.1 on 2023-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_cities_photo_11_cities_photo_12_cities_photo_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='short_discription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='culturalobjects',
            name='discription',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='culturalobjects',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='discription',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='discription',
            field=models.TextField(verbose_name='описание'),
        ),
    ]
