# Generated by Django 4.2.1 on 2023-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_cities_short_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='short_discription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='RouteDetails',
        ),
        migrations.DeleteModel(
            name='Routers',
        ),
    ]
