# Generated by Django 4.2.1 on 2023-06-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_cities_short_discription_delete_routedetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos_routers/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Путкты остановки')),
                ('stopping_points_desc', models.TextField(verbose_name='Описания города')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos_route_details/%Y/%m/%d/', verbose_name='Фото')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.routers', verbose_name='Маршруты')),
            ],
        ),
    ]
