# Generated by Django 4.2.1 on 2023-06-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_routers_routedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='country.routers', verbose_name='Маршруты'),
        ),
    ]
