# Generated by Django 4.2.1 on 2023-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_alter_routedetails_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_ditails',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='country.events', verbose_name='События'),
        ),
    ]
