# Generated by Django 4.2.1 on 2023-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_alter_events_ditails_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_ditails',
            name='where',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведения'),
        ),
    ]
