# Generated by Django 4.2.1 on 2023-06-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_events_ditails_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosdiscriptions',
            name='external_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='country.photos', verbose_name='Рубрика фотографий'),
        ),
    ]
