# Generated by Django 4.2.1 on 2023-06-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_comment_created_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.events'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.photos'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_routers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.routers'),
        ),
    ]
