# Generated by Django 4.2.1 on 2023-06-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_alter_comment_post_events_alter_comment_post_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_cities',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_events',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_photos',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_routers',
        ),
    ]
