# Generated by Django 4.2.1 on 2023-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_alter_comment_active_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
