# Generated by Django 4.2.1 on 2023-06-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_alter_comment_options_remove_comment_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
